#!/usr/bin/env bash
# Regenerate the Homebrew formula for a published version.
#
# A binary formula carries four URLs and four checksums. Editing them by hand is
# how a tap ends up serving one platform's binary under another's checksum, so
# this reads the real release and writes the whole formula from it.
#
#   scripts/update-tap.sh v0.1.0                 # tap checked out at ../homebrew-tap
#   scripts/update-tap.sh v0.1.0 ~/src/homebrew-tap
#
# It writes the file and stops. Review the diff and push yourself — the tap is
# what other people install from.
set -euo pipefail

version=${1:-}
tap=${2:-$(dirname "$0")/../../homebrew-tap}
if [ -z "$version" ]; then
  echo "usage: $(basename "$0") <version> [path-to-homebrew-tap]" >&2
  exit 2
fi
case "$version" in
  v*) ;;
  *) echo "version must look like v0.1.0, got $version" >&2; exit 2 ;;
esac

repo=richarddavenport/pgctl
formula="$tap/Formula/pgctl.rb"
mkdir -p "$(dirname "$formula")"

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# The release, through the API rather than the releases/download CDN. Both serve
# the same bytes and they fail independently: the tool this was taken from hit a
# persistent 503 on every download URL while the API served the same assets
# fine. The formula still POINTS at the download URL, because that is what brew
# fetches; only the verification transport differs.
#
# No token: the repository is public, which is the whole reason a formula can
# fetch from it at all.
api="https://api.github.com/repos/$repo/releases/tags/$version"
release=$work/release.json
curl -fsSL "$api" -o "$release" || {
  echo "no release $version in $repo — is it published?" >&2
  exit 1
}

# Every checksum comes from the release's own checksums.txt, not from
# downloading four binaries.
#
# That is a deliberate difference from the script this came from, which fetched
# each asset and hashed it: the workflow generates checksums.txt with
# `shasum -a 256 *` over the very files it uploads, so it is authoritative for
# what was built, and one 300-byte download beats four of twelve megabytes. What
# it cannot catch is a TRUNCATED upload — and that failure is caught anyway, by
# brew refusing the fetch, which is the loud outcome rather than a formula that
# quietly serves the wrong bytes.
asset_id() {
  awk -v name="$1" '
    /"id":/   { last = $2; sub(/,$/, "", last) }
    /"name":/ { if ($0 ~ "\"" name "\"") { print last; exit } }
  ' "$release"
}

sums_id=$(asset_id checksums.txt)
[ -n "$sums_id" ] || { echo "release $version has no checksums.txt" >&2; exit 1; }
curl -fsSL -H "Accept: application/octet-stream" \
  -o "$work/checksums.txt" "https://api.github.com/repos/$repo/releases/assets/$sums_id" || {
  echo "could not download checksums.txt for $version" >&2
  exit 1
}

# One lookup per platform, and each also proves the asset is actually on the
# release: a checksum for a binary that never uploaded would point brew at a
# 404.
sum_for() {
  name=pgctl-$1
  [ -n "$(asset_id "$name")" ] || { echo "release $version has no asset $name" >&2; exit 1; }
  sum=$(awk -v n="$name" '{ sub(/^\*/, "", $2); if ($2 == n) { print $1; exit } }' "$work/checksums.txt")
  [ -n "$sum" ] || { echo "checksums.txt has no line for $name" >&2; exit 1; }
  printf '%s' "$sum"
}

# Plain variables rather than an associative array: macOS ships bash 3.2, which
# has no `declare -A`, and this script runs on the machine it publishes for.
sha_darwin_arm64=$(sum_for darwin-arm64); echo "  darwin-arm64  $sha_darwin_arm64"
sha_darwin_amd64=$(sum_for darwin-amd64); echo "  darwin-amd64  $sha_darwin_amd64"
sha_linux_arm64=$(sum_for linux-arm64);   echo "  linux-arm64   $sha_linux_arm64"
sha_linux_amd64=$(sum_for linux-amd64);   echo "  linux-amd64   $sha_linux_amd64"

cat > "$formula" <<EOF
# Prebuilt binaries rather than a source build. pgctl is MIT and public, so brew
# COULD compile it — this serves the identical bytes the release does instead,
# which is what makes \`brew upgrade\` and \`pgctl update\` interchangeable rather
# than two builds that happen to share a version number.
#
# Generated by scripts/update-tap.sh in the pgctl repo — edit that, not this.
class Pgctl < Formula
  desc "Move PostgreSQL data between environments: snapshots, refreshes, table-set migrations"
  homepage "https://github.com/$repo"
  license "MIT"
  version "${version#v}"

  on_macos do
    on_arm do
      url "https://github.com/$repo/releases/download/$version/pgctl-darwin-arm64"
      sha256 "${sha_darwin_arm64}"
    end
    on_intel do
      url "https://github.com/$repo/releases/download/$version/pgctl-darwin-amd64"
      sha256 "${sha_darwin_amd64}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/$repo/releases/download/$version/pgctl-linux-arm64"
      sha256 "${sha_linux_arm64}"
    end
    on_intel do
      url "https://github.com/$repo/releases/download/$version/pgctl-linux-amd64"
      sha256 "${sha_linux_amd64}"
    end
  end

  # PostgreSQL 16 or newer, client tools included: below 16 there is no zstd
  # compression, and pgctl's speed starts there. A dependency rather than a
  # caveat, because pg_dump and pg_restore are what it drives.
  depends_on "postgresql@17" => :recommended

  def install
    # The asset is the bare executable, named per platform.
    bin.install Dir["pgctl-*"].first => "pgctl"
  end

  test do
    assert_match "pgctl", shell_output("#{bin}/pgctl version")
  end
end
EOF

echo
echo "wrote $formula for $version"

# tap.sh sets this: it commits and pushes itself, and these instructions would
# name a temp directory it is about to delete.
if [ -z "${PGCTL_TAP_PUSHER:-}" ]; then
  echo
  echo "next:"
  echo "  ruby -c $formula"
  echo "  brew audit --strict --formula richarddavenport/tap/pgctl"
  echo "  git -C $tap commit -am \"pgctl $version\" && git -C $tap push"
fi
